---
# yaml-language-server: $schema=https://crds.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-ceph-charts
  namespace: rook-ceph
spec:
  interval: 12h
  url: https://charts.rook.io/release
