apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- banzaicloud.yaml
- bitnami.yaml
- gitlab.yaml
- grafana.yaml
- jetstack.yaml
- k8s-at-home.yaml
- hashicorp-charts.yaml
- kubernetes-stable.yaml
- node-feature-discovery-charts.yaml
- oauth2-proxy.yaml
- openebs-cstor.yaml
- pomerium.yaml
- prometheus-community.yaml
- rook-release.yaml
- traefik.yaml
- vmware-tanzu.yaml
- vernemq-charts.yaml
- weaveworks-kured.yaml
- stakater-charts.yaml
