---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milton-mcf-io-wc-cert
  namespace: ingress-system
spec:
  secretName: milton-mcf-io-wc-cert-tls
  issuerRef:
    name: letsencrypt-azure
    kind: ClusterIssuer
  dnsNames:
    - milton.mcf.io
    - "*.milton.mcf.io"
