---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.7.4
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    fullnameOverride: grafana
    image:
      tag: 7.5.3
    testFramework:
      enabled: false
    serviceMonitor:
      enabled: true
    admin:
      existingSecret: 'grafana-admin-creds'
      userKey: admin-user
      passwordKey: admin-password
    grafana.ini:
      server:
        root_url: https://grafana.milton.mcf.io
      auth.google:
        enabled: true
        client_id: $__file{/etc/secrets/grafana-auth-google/client_id}
        client_secret: $__file{/etc/secrets/grafana-auth-google/client_secret}
        scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
        auth_url: https://accounts.google.com/o/oauth2/auth
        token_url: https://accounts.google.com/o/oauth2/token
        allowed_domains: mcfaul.cloud
        allow_sign_up: true
    extraSecretMounts:
    - name: grafana-auth-google-mount
      secretName: grafana-auth-google
      defaultMode: 0440
      mountPath: /etc/secrets/grafana-auth-google
      readOnly: true
    sidecar:
      image:
        tag: 1.3.0
      dashboards:
        enabled: true
      datasources:
        enabled: true
      notifiers:
        enabled: true
