apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ceph-admission-controller.yaml
- config-map.yaml
- helm-release.yaml
- ceph-cluster.yaml
- ceph-block-pool.yaml
- storage-class.yaml
- ceph-block-pool-single.yaml
- csi-snapshot-controller
- volume-snapshot-class.yaml
- virtual-service.yaml
