apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
# - config-map.yaml
- operator/helm-release.yaml
# - ceph-cluster.yaml
# - ceph-block-pool.yaml
# - storage-class.yaml
# - ceph-block-pool-single.yaml
# - csi-snapshot-controller
# - volume-snapshot-class.yaml
# - virtual-service.yaml
