---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 6h
  url: ssh://git@github.com/mcfio/home-cluster
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/cluster
