---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.1.16
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  timeout: 20m
  dependsOn:
  - name: kube-prometheus-stack
    namespace: monitoring
  - name: thanos
    namespace: monitoring
  values:
    fullnameOverride: grafana
    image:
      repository: grafana/grafana
      tag: 7.3.6
    testFramework:
      enabled: false
    serviceMonitor:
      enabled: true
    admin:
      existingSecret: 'grafana-admin-creds'
      userKey: admin-user
      passwordKey: admin-password
    grafana.ini:
      server:
        root_url: https://grafana.milton.mcf.io
      auth.google:
        enabled: true
        client_id: $__file{/etc/secrets/grafana-auth-google/client_id}
        client_secret: $__file{/etc/secrets/grafana-auth-google/client_secret}
        scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
        auth_url: https://accounts.google.com/o/oauth2/auth
        token_url: https://accounts.google.com/o/oauth2/token
        allowed_domains: mcfaul.cloud
        allow_sign_up: true
    extraSecretMounts:
    - name: grafana-auth-google-mount
      secretName: grafana-auth-google
      defaultMode: 0440
      mountPath: /etc/secrets/grafana-auth-google
      readOnly: true
    sidecar:
      image:
        tag: 1.3.0
      dashboards:
        enabled: true
      datasources:
        enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://thanos-query-http.monitoring.svc.cluster.local:10902/
          isDefault: true
    plugins:
    - natel-discrete-panel
    - pr0ps-trackmap-panel
    - grafana-piechart-panel
    - vonage-status-panel
    - grafana-worldmap-panel
    - grafana-clock-panel
    - btplc-status-dot-panel
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        istio-control-plane-dashboard:
          gnetId: 7645
          revision: 43
          datasource: Prometheus
        istio-mesh-dashboard:
          gnetId: 7639
          revision: 43
          datasource: Prometheus
        istio-workload-dashboard:
          gnetId: 7630
          revision: 43
          datasource: Prometheus
        istio-service-dashboard:
          gnetId: 7636
          revision: 43
          datasource: Prometheus
        istio-performance-dashboard:
          url: https://raw.githubusercontent.com/istio/istio/master/manifests/addons/dashboards/istio-performance-dashboard.json
          datasource: Prometheus
        istio-pilot-dashboard:
          url: https://raw.githubusercontent.com/istio/istio/master/manifests/addons/dashboards/pilot-dashboard.json
          datasource: Prometheus
        # cert-manager:
        #   url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/raw/master/dashboards/cert-manager.json
        #   datasource: Prometheus
        openebs:
          gnetId: 12171
          revision: 2
          datasource: Prometheus
        openebs-pg-dashboard:
          url: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-pg-dashboard.json
          datasource: Prometheus
        toolkit-cluster:
          url: https://raw.githubusercontent.com/fluxcd/toolkit/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus
        toolkit-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/toolkit/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus
        traefik-dashboard:
          url: https://grafana.com/api/dashboards/12250/revisions/1/download
          datasource: Prometheus
        unifi-udm-insights:
          gnetId: 11313
          revision: 8
          datasource: Prometheus
        unifi-usw-insights:
          gnetId: 11312
          revision: 8
          datasource: Prometheus
        unifi-uap-insights:
          gnetId: 11314
          revision: 9
          datasource: Prometheus
        unifi-client-insights:
          gnetId: 11315
          revision: 8
          datasource: Prometheus
