apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- config-map.yaml
- helm-release.yaml
- ceph-cluster.yaml
- ceph-block-pool.yaml
- storage-class.yaml
- ingress.yaml
