---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-agent
spec:
  interval: 12h
  chart:
    spec:
      chart: gitlab-agent
      version: v2.22.1
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: gitlab-system
  values:
    config:
      kasAddress: wss://kas.gitlab.com
      secretName: gitlab-agent
