---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-operator
spec:
  hostnames:
  - flux.milton.mcf.io
  parentRefs:
  - name: internal
    namespace: ingress-system
  rules:
  - backendRefs:
    - name: flux-operator
      namespace: flux-system
      port: 9080
