---
# yaml-language-server: $schema=https://crds.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-external-dns
spec:
  endpoints:
    - dnsName: ipv4.mcf.io
      recordType: CNAME
      targets:
        - ${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com
