---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: cluster-ip-pool
spec:
  blocks:
  - cidr: 192.168.45.70/32
  - start: 192.168.45.110
    stop: 192.168.45.120
